/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Health
         * @description Liveness plus enough detail to be worth curling.
         *
         *     A health check that only says "ok" tells you nothing you did not already
         *     know from the connection succeeding.
         */
        get: operations["health_api_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/capabilities": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Capabilities
         * @description Which optional features this install has, and how to enable the rest.
         */
        get: operations["capabilities_api_capabilities_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/jobs/search": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Search Jobs */
        post: operations["search_jobs_api_jobs_search_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/jobs/recent": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Recent Jobs */
        get: operations["recent_jobs_api_jobs_recent_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/jobs/saved": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Saved Jobs */
        get: operations["saved_jobs_api_jobs_saved_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/jobs/{job_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Job */
        get: operations["get_job_api_jobs__job_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/jobs/{job_id}/save": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Save Job */
        post: operations["save_job_api_jobs__job_id__save_post"];
        /** Unsave Job */
        delete: operations["unsave_job_api_jobs__job_id__save_delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/resumes/upload": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Upload Resume
         * @description Accept an upload and parse it.
         *
         *     The client-supplied filename is discarded rather than sanitised — only its
         *     extension survives — and the body is streamed to disk with the size cap
         *     enforced as bytes arrive, so an oversized upload cannot fill the disk
         *     before anyone checks.
         */
        post: operations["upload_resume_api_resumes_upload_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/resumes/parse": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Parse Resume Text
         * @description Parse pasted resume text.
         *
         *     There is deliberately no ``path=`` equivalent here. Over HTTP the caller
         *     is not necessarily the person running the server, and a tool that reads
         *     server-side paths on request is a file-disclosure primitive.
         */
        post: operations["parse_resume_text_api_resumes_parse_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/resumes": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Resumes */
        get: operations["list_resumes_api_resumes_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/resumes/{resume_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Resume */
        get: operations["get_resume_api_resumes__resume_id__get"];
        put?: never;
        post?: never;
        /** Delete Resume */
        delete: operations["delete_resume_api_resumes__resume_id__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/match": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Match Jobs */
        post: operations["match_jobs_api_match_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/letters": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Generate Letter */
        post: operations["generate_letter_api_letters_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/letters/{letter_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Letter */
        get: operations["get_letter_api_letters__letter_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** Body_upload_resume_api_resumes_upload_post */
        Body_upload_resume_api_resumes_upload_post: {
            /**
             * File
             * @description A .pdf, .docx, .txt or .md resume.
             */
            file: string;
        };
        /**
         * Capabilities
         * @description What this particular install can actually do.
         *
         *     Exposed as the ``careercraft://capabilities`` resource so a host model can
         *     read it once and stop offering features that would only fail.
         */
        Capabilities: {
            /** Version */
            version: string;
            /** Python */
            python: string;
            /** Transport */
            transport: string;
            /** Capabilities */
            capabilities: components["schemas"]["Capability"][];
            /**
             * Default Match Strategy
             * @enum {string}
             */
            default_match_strategy: "embedding" | "keyword";
        };
        /** Capability */
        Capability: {
            /** Name */
            name: string;
            /** Available */
            available: boolean;
            /**
             * Detail
             * @default
             */
            detail: string;
            /** Enable With */
            enable_with?: string | null;
        };
        /** Contacts */
        Contacts: {
            /** Email */
            email?: string | null;
            /** Phone */
            phone?: string | null;
            /** Linkedin */
            linkedin?: string | null;
            /** Github */
            github?: string | null;
        };
        /** CoverLetter */
        CoverLetter: {
            /** Job Id */
            job_id: string;
            /** Resume Id */
            resume_id?: string | null;
            /**
             * Tone
             * @default professional
             * @enum {string}
             */
            tone: "professional" | "enthusiastic" | "concise" | "academic";
            /**
             * Length
             * @default medium
             * @enum {string}
             */
            length: "short" | "medium" | "long";
            /** Text */
            text?: string | null;
            brief?: components["schemas"]["LetterBrief"] | null;
            /**
             * Generated By
             * @default template
             * @enum {string}
             */
            generated_by: "ollama" | "template" | "brief";
            /** Model */
            model?: string | null;
            /**
             * Word Count
             * @default 0
             */
            word_count: number;
            /**
             * Created At
             * Format: date-time
             */
            created_at?: string;
        };
        /** EducationEntry */
        EducationEntry: {
            /** Text */
            text: string;
            /** Degree */
            degree?: string | null;
            /** Years */
            years?: string[];
        };
        /** ExperienceEntry */
        ExperienceEntry: {
            /**
             * Organization
             * @default
             */
            organization: string;
            /**
             * Title
             * @default
             */
            title: string;
            /** Period */
            period?: string | null;
            /** Highlights */
            highlights?: string[];
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** HealthResponse */
        HealthResponse: {
            /** Status */
            status: string;
            /** Version */
            version: string;
            /** Llm Available */
            llm_available: boolean;
            /** Stats */
            stats: {
                [key: string]: number;
            };
        };
        /**
         * Job
         * @description A single job posting, normalised across sources.
         */
        Job: {
            /**
             * Id
             * @description Stable content hash; the same posting always gets the same id.
             */
            id: string;
            /** Title */
            title: string;
            /**
             * Company
             * @default
             */
            company: string;
            /**
             * Location
             * @default Remote
             */
            location: string;
            /**
             * Description
             * @default
             */
            description: string;
            /**
             * Url
             * @default
             */
            url: string;
            /**
             * Source
             * @default
             */
            source: string;
            /**
             * Level
             * @default
             */
            level: string;
            /**
             * Job Type
             * @default
             */
            job_type: string;
            /**
             * Salary
             * @default
             */
            salary: string;
            /** Published At */
            published_at?: string | null;
            /**
             * Fetched At
             * Format: date-time
             */
            fetched_at?: string;
        };
        /** JobMatch */
        JobMatch: {
            job: components["schemas"]["Job"];
            /**
             * Score
             * @description 0-1; comparable only within one strategy.
             */
            score: number;
            /** Matched Skills */
            matched_skills?: string[];
            /**
             * Missing Skills
             * @description Skills the posting emphasises that the resume does not mention.
             */
            missing_skills?: string[];
            /**
             * Rationale
             * @default
             */
            rationale: string;
        };
        /** JobSearchResult */
        JobSearchResult: {
            /** Jobs */
            jobs: components["schemas"]["Job"][];
            /** Total */
            total: number;
            /**
             * Query
             * @default
             */
            query: string;
            /**
             * Location
             * @default
             */
            location: string;
            /**
             * From Cache
             * @default false
             */
            from_cache: boolean;
            /**
             * Source
             * @default
             */
            source: string;
        };
        /**
         * LetterBrief
         * @description What to say, when no language model is available to say it.
         *
         *     Returned instead of prose when Ollama is unreachable. The MCP host's own
         *     model is generally *better* at writing the letter than a local 1B model —
         *     it just needs the grounded material, which is what this is.
         */
        LetterBrief: {
            /** Company */
            company: string;
            /** Role */
            role: string;
            /** Opening Hook */
            opening_hook: string;
            /** Themes */
            themes: string[];
            /** Evidence */
            evidence: string[];
            /** Company Hooks */
            company_hooks: string[];
            /** Closing */
            closing: string;
            /** Paragraph Plan */
            paragraph_plan: string[];
        };
        /** LetterRequest */
        LetterRequest: {
            /** Job Id */
            job_id: string;
            /** Resume Id */
            resume_id?: string | null;
            /**
             * Tone
             * @default professional
             * @enum {string}
             */
            tone: "professional" | "enthusiastic" | "concise" | "academic";
            /**
             * Length
             * @default medium
             * @enum {string}
             */
            length: "short" | "medium" | "long";
            /** Model */
            model?: string | null;
            /**
             * Allow Brief
             * @description The web UI has no model to hand a brief to, so it defaults to false and gets finished prose from the template instead.
             * @default false
             */
            allow_brief: boolean;
        };
        /**
         * LetterResponse
         * @description A generated letter plus the id it was stored under.
         */
        LetterResponse: {
            /** Id */
            id: string;
            letter: components["schemas"]["CoverLetter"];
        };
        /** MatchRequest */
        MatchRequest: {
            /** Resume Id */
            resume_id?: string | null;
            /**
             * Query
             * @default
             */
            query: string;
            /**
             * Location
             * @default
             */
            location: string;
            /**
             * Top K
             * @default 10
             */
            top_k: number;
            /**
             * Min Score
             * @default 0.15
             */
            min_score: number;
            /**
             * Strategy
             * @default auto
             * @enum {string}
             */
            strategy: "auto" | "embedding" | "keyword";
            /**
             * Filter Seniority
             * @default true
             */
            filter_seniority: boolean;
        };
        /** MatchResult */
        MatchResult: {
            /** Matches */
            matches: components["schemas"]["JobMatch"][];
            /**
             * Strategy Used
             * @enum {string}
             */
            strategy_used: "embedding" | "keyword";
            /**
             * Candidate Is Junior
             * @default false
             */
            candidate_is_junior: boolean;
            /**
             * Jobs Considered
             * @default 0
             */
            jobs_considered: number;
            /**
             * Jobs Filtered Out
             * @default 0
             */
            jobs_filtered_out: number;
            /** Notes */
            notes?: string[];
        };
        /** ParseTextRequest */
        ParseTextRequest: {
            /** Text */
            text: string;
            /** Source Name */
            source_name?: string | null;
            /**
             * Persist
             * @default true
             */
            persist: boolean;
        };
        /**
         * ParsedResume
         * @description The output of resume parsing, and the input to matching.
         */
        ParsedResume: {
            /**
             * Id
             * @default
             */
            id: string;
            /** Name */
            name?: string | null;
            contacts?: components["schemas"]["Contacts"];
            /** Skills */
            skills?: string[];
            /** Education */
            education?: components["schemas"]["EducationEntry"][];
            /** Experience */
            experience?: components["schemas"]["ExperienceEntry"][];
            /** Projects */
            projects?: components["schemas"]["ProjectEntry"][];
            /**
             * Raw Length
             * @default 0
             */
            raw_length: number;
            /** Sections Detected */
            sections_detected?: string[];
            /** Parse Warnings */
            parse_warnings?: string[];
            /**
             * Backend
             * @default regex
             */
            backend: string;
            /**
             * Used Ocr
             * @default false
             */
            used_ocr: boolean;
            /** Source Name */
            source_name?: string | null;
            /**
             * Parsed At
             * Format: date-time
             */
            parsed_at?: string;
        };
        /** ProjectEntry */
        ProjectEntry: {
            /**
             * Name
             * @default
             */
            name: string;
            /** Role */
            role?: string | null;
            /** Location */
            location?: string | null;
            /** Period */
            period?: string | null;
            /** Highlights */
            highlights?: string[];
        };
        /**
         * ResumeSummary
         * @description A row in ``list_resumes`` — enough to pick one, not the whole document.
         */
        ResumeSummary: {
            /** Id */
            id: string;
            /** Name */
            name?: string | null;
            /** Source Name */
            source_name?: string | null;
            /**
             * Skills Count
             * @default 0
             */
            skills_count: number;
            /**
             * Experience Count
             * @default 0
             */
            experience_count: number;
            /**
             * Parsed At
             * Format: date-time
             */
            parsed_at: string;
        };
        /** SaveJobRequest */
        SaveJobRequest: {
            /**
             * Note
             * @default
             */
            note: string;
        };
        /** SavedJob */
        SavedJob: {
            job: components["schemas"]["Job"];
            /**
             * Note
             * @default
             */
            note: string;
        };
        /** SearchRequest */
        SearchRequest: {
            /**
             * Query
             * @default
             */
            query: string;
            /**
             * Location
             * @default
             */
            location: string;
            /**
             * Limit
             * @default 25
             */
            limit: number;
            /**
             * Remote Only
             * @default true
             */
            remote_only: boolean;
            /**
             * Refresh
             * @default false
             */
            refresh: boolean;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    health_api_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthResponse"];
                };
            };
        };
    };
    capabilities_api_capabilities_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Capabilities"];
                };
            };
        };
    };
    search_jobs_api_jobs_search_post: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SearchRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["JobSearchResult"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    recent_jobs_api_jobs_recent_get: {
        parameters: {
            query?: {
                limit?: number;
            };
            header?: {
                authorization?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Job"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    saved_jobs_api_jobs_saved_get: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SavedJob"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_job_api_jobs__job_id__get: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path: {
                job_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Job"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    save_job_api_jobs__job_id__save_post: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path: {
                job_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SaveJobRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Job"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    unsave_job_api_jobs__job_id__save_delete: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path: {
                job_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    upload_resume_api_resumes_upload_post: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "multipart/form-data": components["schemas"]["Body_upload_resume_api_resumes_upload_post"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ParsedResume"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    parse_resume_text_api_resumes_parse_post: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ParseTextRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ParsedResume"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_resumes_api_resumes_get: {
        parameters: {
            query?: {
                limit?: number;
            };
            header?: {
                authorization?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ResumeSummary"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_resume_api_resumes__resume_id__get: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path: {
                resume_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ParsedResume"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_resume_api_resumes__resume_id__delete: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path: {
                resume_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    match_jobs_api_match_post: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["MatchRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MatchResult"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    generate_letter_api_letters_post: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LetterRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LetterResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_letter_api_letters__letter_id__get: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path: {
                letter_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CoverLetter"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
